- docs/source/tutorial.rst
- tests/test_rest_api.py
- xpublish/rest.py
Adding `init_app` method to set additional configuration to `FastAPI` configuration to allow more control to app and expand.
Need this for sub-application to build proxying for multiple datasets: https://fastapi.tiangolo.com/advanced/sub-applications-proxy/
> Add init app method for custom app config

- xpublish/rest.py
This fixes problem with encoding for JSON Response of the zmetadata.
I ran into `UnicodeDecodeError` when trying to read one of my dataset that has been published.
```python
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10229: ordinal not in range(128)
```
Based on the error it seems that the zarr library uses 'ascii' decoder to decode the json zmetadata. However, xpublish currently uses 'utf-8' encoding.
```python
/opt/conda/envs/xpub/lib/python3.6/site-packages/zarr/util.py in json_loads(s)
28 def json_loads(s):
29     """Read JSON in a consistent way."""
---> 30     return json.loads(ensure_text(s, 'ascii'))
31 
32 
```
The solution in this PR ensures that the zmetadata json is encoded with 'ascii' rather than 'utf-8'.
> Fix unicode decode error

- xpublish/rest.py
This PR fixes #7.
It appears that there was a clash/confusion between the uvicorn event loop and the dask distributed event loop. When using `async` in a FastAPI app, this method will be sent to the uvicorn event loop. So the request for individual chunks were processed concurrently. Each dask compute becomes blocking and is only processed by one worker which I think is part of the uvicron event loop.
To allow dask to actually compute in parallel the async and await for `get_key` should be remove, which frees up this method to use the compute within dask distributed event loop rather than the uvicorn event loop.
> Fix async clash with dask

- setup.cfg
- tests/test_zarr_compat.py
- tests/utils.py
- xpublish/rest.py
In light of https://github.com/jhamman/xpublish/issues/7#issuecomment-591785407,  I am adding a utility function to create synthetic data for testing purposes.
> Add more tests

- README.rst
- docs/source/index.rst
- docs/source/tutorial.rst
- tests/test_rest_api.py
- xpublish/rest.py
- xpublish/utils/api.py
Follow-up #27.
Custom API routers may be plugged in the FastAPI application using the new `routers` argument when calling the `rest` accessor. This completely overrides the default routers, although it is still possible to reuse the latter ones by importing them from `xpublish.routers` and including them in the given list of routers.
TODO:
> Custom routes

- .readthedocs.yml
- docs/requirements.txt
- docs/source/api.rst
- docs/source/conf.py
- docs/source/contributing.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/tutorial.rst
- setup.cfg
- xpublish/dependencies.py
- xpublish/rest.py
A couple of comments:
- The `rest` accessor API is now documented using [sphinx-autosummary-accessors](https://github.com/keewis/sphinx-autosummary-accessors).
- I replaced the ipython directives by regular python code blocks. I don't think using ipython directives are worth relying on ipython + all xpublish's runtime dependencies for building the docs, given that we don't really leverage the interactive output here. I'm not against reverting this change in case anyone has objections.
> Doc fixes, tweaks and improvements

- docs/requirements.txt
- docs/source/contributing.rst
I just moved `sphinx-autosummary-accessors` from my own organization to `xarray-contrib`. Since right now it's only used by the repositories in `xarray-contrib` I can afford to submit PRs to all of them :grinning:
Not sure when I can release that extension and upload to PyPI / conda-forge (that is blocked by issues with `AccessorCallable` in combination with `autosummary` – once fixed the `alias of ...` summary will be replaced by the summary line in the `__call__` docstring), but once I do I'll ping you.
> update the package url for sphinx-autosummary-accessors

- docs/requirements.txt
- docs/source/contributing.rst
As it has moved to the `xarray-contrib` organization.
> Update URL of sphinx-autosummary-accessors repo

- docs/requirements.txt
I just released `sphinx-autosummary-accessors` 0.1, so that should be preferred over installing from github. This also pins `sphinx` to `sphinx>=3.1` which fixes the incomplete summary for callable accessors.
> use the released version from pypi

- docs/source/api.rst
- docs/source/index.rst
- docs/source/tutorial.rst
- tests/test_core.py
- tests/test_fsspec_compat.py
- tests/test_rest_api.py
- tests/test_zarr_compat.py
- xpublish/__init__.py
- xpublish/dependencies.py
- xpublish/rest.py
- xpublish/routers/__init__.py
- xpublish/routers/common.py
- xpublish/routers/zarr.py
- xpublish/utils/api.py
- xpublish/utils/zarr.py
Closes #23.
It took me a bit longer than I thought to implement this.
TODO:
---
This PR adds a top-level ``Rest`` class that has the same interface than the `Dataset.rest` accessor. Actually, the accessor now internally reuses this class and is just there for convenience:
```python
ds.rest.serve()
```
is equivalent to
```python
Rest(ds).serve()
```
When ~~``unique=False``~~ a mapping of datasets is given to `Rest.__init__`, all dataset-specific api endoints have the prefix ``/datasets/{dataset_id}``. There is also another endpoint ``/datasets`` that returns a list of all dataset ids. When ~~``unique=True``~~ a single dataset is given the behavior stays unchanged compared to the current one.
Some other remarks on the implementation:
- All the datasets in the published collection have an …
> Publish a collection of datasets

- .coveragerc
- dev-requirements.txt
- tests/test_core.py
- tests/test_rest_api.py
- xpublish/__init__.py
- xpublish/dependencies.py
- xpublish/rest.py
- xpublish/routers/common.py
- xpublish/utils/info.py
- xpublish/utils/zarr.py
Includes #38 so should be reviewed after the merge of that PR.
> Bring test coverage to 100%

- tests/test_rest_api.py
- xpublish/rest.py
- xpublish/utils/api.py
This fixes FastAPI's generated API docs in the case where a single dataset is published. The `dataset_id` parameter is not shown anymore.
The fix is based on FastAPI docs: https://fastapi.tiangolo.com/advanced/extending-openapi/. I had to do some tricks to support a bunch of changes in last FastAPI versions, though. Hopefully it won't change too often in the future.
This fix won't be needed anymore if it is addressed upstream (see https://github.com/tiangolo/fastapi/issues/1594).
> Fix single dataset openapi specs (API docs)

- xpublish/utils/info.py
otherwise this may happen  on the /versions route:
```
File "/home/mah/.local/lib/python3.7/site-packages/xpublish/utils/info.py", line 38, in get_sys_info
blob.append(('commit', commit))
UnboundLocalError: local variable 'commit' referenced before assignment
```
> 🐛Do not fail if not a git repo when retrieving system information

- dev-requirements.txt
- xpublish/utils/zarr.py
Xpublish is currently failing as Dask array functions need to be explicitly imported as `import dask.array` rather than being accessible via `import dask`.
Closes #135
> Import dask.array to access to array functions

- tests/test_rest_api.py
- xpublish/plugins/included/dataset_info.py
Multiple requests to the /info endpoint are failing. The DatasetInfoPlugin is changing the cached metadata by removing the `_ARRAY_DIMENSIONS` attribute key which is required on subsequent calls. I did not dive into the caching internals to figure out why the value is mutable at all. If it is a simple dict on the backend, the returned cache values could be being changed inside the cache dict itself.
Added a test that fails without the change!
> Don't mutate cached data in DatasetInfoPlugin

- docs/requirements.txt
- docs/source/contributing.rst
- setup.cfg
* Fix references to the `master` branch
* Follow the CI method to bootstrap an env
* Install from and fix the docs requirements file
* Add default pytest arguments to setup.cfg
> Contrib docs cleanup

- tests/conftest.py
- tests/test_fsspec_compat.py
- tests/test_rest_api.py
- xpublish/plugins/included/dataset_info.py
- xpublish/plugins/included/zarr.py
- xpublish/utils/api.py
Datasets with `NaN` value attributes currently raise a `ValueError: Out of range float values are not JSON compliant` error. This adds a `starlette.responses.JsonResponse` subclass that explicitly allows nan values. The class is taken [straight from starlette](https://github.com/encode/starlette/blob/58b82b07b913645fa968a4e23a0707226f56fe97/starlette/responses.py#L194-L201) and only changes the `allow_nan` parameter.
> Allow NaN attributes in datasets

- .readthedocs.yml
- docs/Makefile
- docs/requirements.txt
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/plugins.rst
- xpublish/plugins/hooks.py
I've introduced the plugin system with descriptions and examples for the 4 main kinds of plugins (app/dataset routers, dataset providers, and hook spec). I've also tried to explain the common functionality and enough of the underlying system to get folks started building their own.
@kwilcox @mpiannucci I'd love your feedback as I'm pretty sure you are both using plugins, and I'd love to hear from anyone else using plugins to about these docs and if there is anything that would help improve them.
> Plugin documentation

- docs/Makefile
- docs/requirements.txt
- docs/source/api.rst
- docs/source/conf.py
- xpublish/dependencies.py
- xpublish/rest.py
Currently the API docs are missing a bunch of `xpublish.Rest` methods, so this fills them out. It also switches to using type hints directly in the docs rather than requiring them to be specified in the docstrings.
Closes #160 #161
I'm headed out on vacation, so feel free to edit or merge away, otherwise if there aren't any complaints I'll land it when I get back.
> Add methods to API docs and use typehints

- tests/test_zarr_compat.py
- tests/utils.py
- xpublish/utils/zarr.py
See #175 
Previously, the coordinates of each DataArray were not encoded, only the dims were. So we couldnt plot this how it is shown below. 
Tested with: 
```python
fs = HTTPFileSystem()
http_map = fs.get_mapper("http://0.0.0.0:8090/datasets/dbofs")
ds = xr.open_zarr(http_map, consolidated=True)
ds.temp.isel(ocean_time=0, s_rho=0).plot(x='lon_rho', y='lat_rho', cmap='jet')
```
> Encode coords for zarr router

- tests/test_core.py
- tests/test_rest_api.py
- xpublish/rest.py
If a single dataset is passed to `xpublish.Rest` it now throws a `TypeError` directing the user to use `xpublish.SingleDatasetRest`.
I also found a few tests that were testing other things, but were passing a single dataset to `xpublish.Rest`.
Closes #149
> Add TypeError on single dataset

- .github/workflows/main.yaml
- dev-requirements.txt
- requirements.txt
- setup.py
Previously, some of the Xpublish's dependencies had lower bounds. However, these lower bounds were far out of date. They have been removed. Python 3.8 was also removed from our CI system.
BREAKING CHANGE: drop python 3.8 support
(towards debugging #188)
> build: Remove minimum versions in requirements.txt, drop python 3.8

- tests/test_rest_api.py
- tests/test_zarr_compat.py
- tests/utils.py
- xpublish/plugins/included/zarr.py
- xpublish/utils/zarr.py
> Set default ZarrPlugin prefix to /zarr

- tests/test_zarr_compat.py
- xpublish/utils/zarr.py
Reading scalar variables through the zarr plugin is erroring with a `ValueError: Invalid chunk_id for numpy array: 0. Should have been: ()`. This is due to `((0,) * da.ndim)` being `()` when `ndims = 0`. In turn, that does not match the requested chunk `(0,)` so the exception is raised.. This removes the invalid `chunk_id` check when dealing with scalar variables (`ndim = 0`). The added test fails without the change.
> Support reading scalar variables through the zarr plugin

- .github/workflows/main.yaml
Pip was using the same cache for multiple versions, so for Python version specific packages they were almost always missing the cache.
This PR keeps a cache per Python version and separate ones for the upstream tests as well. The cache restore keys allow sharing between versions or between the upstream and regular tests.
> Separate pip caches

- docs/source/ecosystem/index.md
Add's LimnoTech's Catalog-to-Xpublish to the server distributions on the ecosystem page.
> Add Catalog to Xpublish to distros

- dev-requirements.txt
- requirements.txt
v2023.09.0 of Xarray caused our Zarr roundtrip tests to fail as times no longer matched.
For full details see https://github.com/xpublish-community/xpublish/issues/237
The fix looks to have landed in https://github.com/pydata/xarray/pull/8272 and tests against the latest commit works, so we'll go with setting an pin to skip just v2023.09.0.
Closes #237
> Anti-pin the latest version of Xarray to fix Zarr roundtrip tests

- .github/workflows/main.yaml
- .pre-commit-config.yaml
- pyproject.toml
- xpublish/__init__.py
- xpublish/plugins/manage.py
Expand tests to run against Python 3.12, and update Pre-Commit hooks.
> Test against Python 3.12

- dev-requirements.txt
- pyproject.toml
- tests/test_rest_api.py
- tests/utils.py
- xpublish/__init__.py
- xpublish/accessor.py
- xpublish/dependencies.py
- xpublish/plugins/hooks.py
- xpublish/plugins/included/dataset_info.py
- xpublish/plugins/included/module_version.py
- xpublish/plugins/included/plugin_info.py
- xpublish/plugins/included/zarr.py
- xpublish/plugins/manage.py
- xpublish/rest.py
- xpublish/routers/common.py
- xpublish/utils/api.py
- xpublish/utils/cache.py
- xpublish/utils/info.py
- xpublish/utils/zarr.py
Closes #186 
@abkfenris I will be a free-agent in a week or two, and plan to contribute in this ecosystem more heavily. I figured documenting and type-hinting the codebase would be an opportunity to refresh on the inner-workings.
**Changes:**
* I added [Ruff's `pydocstyle`](https://docs.astral.sh/ruff/settings/#pydocstyle) to our `pyproject.toml`. This includes docstring formatting as part of the pre-commit. I have it set to ignore the tests/ and docs/ directories as that seems fussy, but I am happy to cover those two as well. 
* I also have it set to ignore three [docstring rules](https://docs.astral.sh/ruff/rules/#pydocstyle-d), D100 (requires docstrings for all modules / .py files), D107 (requires docstrings for all __init__.py), and D104 (simular to D107, requires all packages to have …
> Docstring improvements

- docs/source/user-guide/plugins.md
- tests/test_core.py
- tests/test_rest_api.py
- xpublish/dependencies.py
- xpublish/plugins/included/dataset_info.py
- xpublish/plugins/included/zarr.py
- xpublish/rest.py
- xpublish/utils/zarr.py
We have been working on building a subset router (https://github.com/asascience-open/xreds/blob/fa3aa81e398c280cef34fd6e0846880df0bb2aef/xreds/plugins/subset_plugin.py#L138) which introduces a nested dataset router. The core zarr plugin did not work with this because of zmetadata and zvariable dependencies using the xpublish global get_dataset dependency. Instead this simply moves those functions to utils and removes the Depends functionality. If there is a better way to handle this i am all ears, I was not sure of why they were dependencies in the first place so this may be incorrect.
This also includes a patch for numpy arrays when using the zarr router (https://github.com/xpublish-community/xpublish/issues/207). In some cases (especially kerchunk concatenated datasets) there may be a …
> Convert zarr helpers to utilities, update numpy chunk encoding in zarr router

- .github/workflows/main.yaml
- requirements.txt
Zarr's updates for v3 have some new dependencies and have shuffled around some functionality that Xpublish uses, so lets limit the maximum version that Xpublish supports for now.
> Pin Zarr to <3

- docs/requirements.txt
- tests/test_core.py
- xpublish/plugins/included/dataset_info.py
- xpublish/plugins/included/zarr.py
- xpublish/utils/zarr.py
Xpublish should be zarr python version agnostic, this is the first step in getting xpublish running with zarr python 3
> Vendor zarr imports

- tests/test_core.py
- xpublish/utils/zarr.py
- fixes .zmetadata chunksizes for dask arrays
- fixes warning when .zmetadata filters is an empty array
- fixes serialization issues for .zmetadata filters
- added empty `region` parameter to `extract_zarr_variable_encoding`, as the downstream call to `_determine_zarr_chunks` requires that parameter
> Zarr Endpoint Compatibility Improvements
